export const FILTRO_ORIGEN = "FILTRO_ORIGEN"
export const FILTRO_TEMP = "FILTRO_TEMP"
export const ORDEN_NAME = "ORDEN_NAME"
export const ORDEN_PESO = "ORDEN_PESO"
export const SET_API_DOGS = "SET_API_DOGS"
export const SET_API_TEMPERAMENTOS = "SET_API_TEMPERAMENTOS"
export const SET_DB_DOGS = "SET_DB_DOGS"
export const SET_DB_TEMP = "SET_DB_TEMP"
export const SET_INTERMEDIA = "SET_INTERMEDIA"
export const CLEAR = "CLEAR"
export const CREATE_DOG = "CREATE_DOG"
export const SEARCH_DOG = "SEARCH_DOG"
export const CREADO = "CREADO"


